### ISSUE TITLE
Add support for secure MySQL 5.7+

### ISSUE THREAD

**Issue by runelynx** [Gamealition/GPrism#13]
Hi -

I see in your list of changes you've added useSSL=false to remove spam, but I went the secure route when I went up to MySQL 5.7. I'm struggling with database plugins now even though usage could be very simple with the right parameters. 

Could you please make these 2 parameters configurable based on the YML?

?verifyServerCertificate=false&useSSL=true

BanManager did this for me, detailed in this issue:
https://github.com/BanManagement/BanManager/issues/738

I'd really appreciate it.

**Comment by RoyCurtis** [comment]
Sorry for the delay in responding,

I've currently lost motivation in anything Minecraft related, so it is difficult for me to attend to issue reports at the moment.

Although this seems like a simple change, I would still prefer to test it in case it breaks GPrism operation. Can anybody else assist in making this change and testing it, please?

**Comment by RoyCurtis** [comment]
Thank you very much @PugaBear for resolving this with a PR!

And thank you @runelynx for the original suggestion; both are appreciated :)

**Comment by runelynx** [comment]
Thank you both so much 👍
