### ISSUE TITLE
Parrot Class not Found

### ISSUE THREAD

**Issue by xtechgamer735** [Gamealition/GPrism#15]
Hello!

Getting this stacktrace spammed in console - looks like it is unable to find the parrot class!

https://pastebin.com/6sEmQ8mA

**Comment by RoyCurtis** [comment]
Thanks for reporting; however, this is happening as you are attempting to run the 1.12 pre-release version (`Prism v1.12pre2-2.0.11`) of GPrism on a 1.11.2 server (`spigot-1.11.2.jar`). Hence, the Parrot class is being reported as missing. I don't develop GPrism with backward compatibility in mind, sorry!

**Comment by xtechgamer735** [comment]
I see thank you! Cant believe I didn't notice that to be honest... Was probably tired. Ive downgraded and we will see how that goes!

Many thanks

**Comment by RoyCurtis** [comment]
No problem; can relate. Good luck!
